on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@master
      
    - name: Hello world action step
      id: costs
      uses: agup006/hello-world-javascript-action@v4
      with:
        yaml-file: 'a.yml'

    - name: Get the output time
      run: echo "The cost was ${{ steps.costs.outputs.cost }}"
